; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs    = mzeroUSB
extra_configs   =
    *_env.ini

[common]
build_flags       =
  -Og
  -g3
  -fno-reorder-blocks
  -Wall
  -Wextra
build_unflags     = -Os
debug_build_flags = -DDEBUG -g3 -Og
debug_init_break  = tbreak setup
lib_deps          =
    tcmenu/IoAbstraction@~4.4.0
    tcmenu/TaskManagerIO@~1.5.1
    wollewald/ADS1115_WE@~1.5.4
    robtillaart/CRC@^1.0.3
    dlloydev/QuickPID@~3.1.9
platform          = atmelsam@~8.3.0
framework         = arduino
lib_ldf_mode      = chain
extra_scripts     =
    copy_hex.py
    lss.py

[env:mzeroUSB]
extends = common
board   = mzeroUSB
