; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs    = esp32dev-ota
extra_configs   =
  *_env.ini

[common]
build_flags     =
    -DCORE_DEBUG_LEVEL=5
    '-DHOSTNAME=${local.hostname}'
    '-DOTA_PASSWORD=${local.ota_password}'
    '-DWIFI_SSID=${local.wifi_ssid}'
    '-DWIFI_PASSWORD=${local.wifi_password}'
lib_deps        =
    tcmenu/IoAbstraction@~4.4.0
    tcmenu/TaskManagerIO@~1.5.1
    olikraus/U8g2@~2.36.8
platform        = espressif32@~6.11.0
board           = esp32dev
framework       = arduino
lib_ldf_mode    = chain
extra_scripts   =

[env:esp32dev-esp-prog]
extends         = common
debug_tool      = esp-prog
upload_protocol = esp-prog

[env:esp32dev-ota]
extends         = common
debug_tool      = esp-prog
upload_protocol = espota
upload_port     = ${local.hostname}.local
upload_flags    =
    --port=3232
    --auth=${local.ota_password}

[env:esp32dev-serial]
extends       = common
debug_tool    = esp-prog
monitor_speed = 115200
